### ISSUE TITLE
Can't save data to MINIO

### ISSUE THREAD

**Issue by doxenix** [flopach/digits-recognizer-kubeflow#1]
Hello,
I deploy Kubeflow using Vanilla deployment [link](https://awslabs.github.io/kubeflow-manifests/docs/deployment/vanilla/guide-terraform/)

**minio version:** 7.1.12

I'm able to login to MINIO UI using defined credentials, however in first step:

```
from minio import Minio
import os

minio_client = Minio(
        "100.65.11.110:9000",
        access_key="minio",
        secret_key="minio123",
        secure=False
    )
minio_bucket = "mlpipeline"


import glob

def upload_local_directory_to_minio(local_path, bucket_name, minio_path):
    assert os.path.isdir(local_path)

    for local_file in glob.glob(local_path + '/**'):
        local_file = local_file.replace(os.sep, "/") # Replace \ with / on Windows
        if not os.path.isfile(local_file):
            upload_local_directory_to_minio(
                local_file, bucket_name, minio_path + "/" + os.path.basename(local_file))
        else:
            remote_path = os.path.join(
                minio_path, local_file[1 + len(local_path):])
            remote_path = remote_path.replace(
                os.sep, "/")  # Replace \ with / on Windows
            minio_client.fput_object(bucket_name, remote_path, local_file)
            
upload_local_directory_to_minio("models/detect-digits",minio_bucket,"/models/detect-digits")
```

I'm getting error: 

**HTTPConnectionPool(host='100.65.11.110', port=9000): Max retries exceeded with url: /mlpipeline?location= (Caused by ResponseError('too many 503 error responses'))**

What the reasone could be in this case?

**Comment by doxenix** [comment]
The reason was wrong host name in minio_client.

To check your Minio host name:
`kubectl get pods -n kubeflow | grep minio`

Copy your pod name
`kubectl logs your-minio-pod-name -n kubeflow`

You get:
`Endpoint:  http://10.0.117.227:9000  http://127.0.0.1:9000`

My host name is:
` http://10.0.117.227:900
`
So after correction:
```
minio_client = Minio(
        "100.65.11.110:9000",
        access_key="minio",
        secret_key="minio123",
        secure=False
    )
```

**Comment by doxenix** [comment]
You should also correct line:
`upload_local_directory_to_minio("models/detect-digits",minio_bucket,"/models/detect-digits")`

On (no slash):
`upload_local_directory_to_minio("models/detect-digits",minio_bucket,"models/detect-digits")`

**Comment by flopach** [comment]
Thanks @doxenix! Indeed, I did not write that the user need to set their minio IP. That can be different for every cluster.

I double checked and I in the latest version I removed the slash from the path. Using no slash worked for me.
